- source/Mafia.WidescreenFix/dllmain.cpp
The function that takes desired drawing distance as 3rd argument is also called from separate codepath to set it for cutscenes independently. The hardcoded argument value is 300, this patch sets it according to user wishes.
> Mafia - cutscene draw distance

- source/TonyHawksProSkater3.WidescreenFix/dllmain.cpp
Presumably a typo, the shl instruction was overwritten by MakeInline but not implemented in HudHook causing issue #322.
> THPS3 FixHUD Fix

- source/SonicHeroes.WidescreenFix/dllmain.cpp
Heroes should have it's vertical FOV scaled if it goes below the specified aspect ratio to prevent HUD elements and other important things from being clipped off. I'd also like for the additional field of view to be adjustable here too.
> Heroes Vertical aspect direction + Zoom Scale

- source/SonicHeroes.WidescreenFix/dllmain.cpp
Tested it with the v141 build tools this time, finally made a perfect fix which most of the orthographic elements now stay in 4:3 region without stretching.
> Perfect widescreen for Heroes take 2

- source/NFSUnderground2.WidescreenFix/dllmain.cpp
g_AnimatedTextureEnable needs to be enabled by default since there's no way to do that in-game. Some people were having issues with this.
> NFSU2 WriteSettingsToFile update

- source/NFSMostWanted.WidescreenFix/dllmain.cpp
I'm not sure what the point of this code was, but this is the reason the widescreen mode keeps getting saved to people's profiles.
https://github.com/ThirteenAG/WidescreenFixesPack/blob/69b8633b892d48c258afe1c2f42677584cbbe1d5/source/NFSMostWanted.WidescreenFix/dllmain.cpp#L266-L274
**Line 272** is writing 1 to an address used for profile data that determines if widescreen mode is on or off. When someone creates a new profile this value gets written. This is completely unnecessary because you already have code that enables widescreen mode without affecting the profile:
https://github.com/ThirteenAG/WidescreenFixesPack/blob/69b8633b892d48c258afe1c2f42677584cbbe1d5/source/NFSMostWanted.WidescreenFix/dllmain.cpp#L260-L263
Removing it won't fix existing profiles, but it should prevent the …
> [NFSMW] removed unnecessary widescreen hud code

- source/NFSCarbon.WidescreenFix/dllmain.cpp
- LightingFix values have been updated to match the Xbox 360 version as accurately as possible.
- Code has been added to fix the vertical alignment of  road (water) reflections. I achieved this by replacing the game's default value of 256 with a value of 240.
- Code that increased the mirror resolution, also known as "PiP pixelation", has been removed. This was made obsolete with the existence of [HD Reflections](https://nfsmods.xyz/mod/1044), which gives users full control over the mirror resolution.
> [NFSC] LightingFix and water reflection update

- source/SilentHill2.WidescreenFix/dllmain.cpp
I integrated the code into [Silent-Hill-2-Enhancements](https://github.com/elishacloud/Silent-Hill-2-Enhancements) project.  This project has the warning level set to 4 and I was getting a lot warnings from the code.  Made some minor changes to remove the warnings.
> Fix compiler warnings Silent Hill 2

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- Revised the INI comments for all NFS games. I corrected grammar, improved readability, and added more information.
- Added code for the [extended controller options](https://github.com/ThirteenAG/WidescreenFixesPack/issues/649#issuecomment-485494196) posted by nlgzrgn.
- This has been added as "ExpandControllerOptions" in the INI file. I made it a separate feature since it crashes the game if you don't create a new profile for it.
- Added code for [shadow bug fixes](https://github.com/ThirteenAG/WidescreenFixesPack/issues/594#issuecomment-532379907). This was tested by various people, including myself, and has been confirmed working.
- Removed some rearview mirror code that's no longer needed.
> [NFS] shadow fixes, controller options, revised ini

- data/KnightRider.WidescreenFix/scripts/modupdater.ini
- data/KnightRider2.WidescreenFix/scripts/modupdater.ini
- data/SplinterCell.WidescreenFix/system/scripts/modupdater.ini
- data/SplinterCellPandoraTomorrow.WidescreenFix/offline/system/scripts/modupdater.ini
The password for the archives available on http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html has been update to `shitgoogle` (from `dege`).
> Update dgVoodoo password

- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/SilentHill3.WidescreenFix/scripts/SilentHill3.WidescreenFix.ini
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
- source/SilentHill3.WidescreenFix/dllmain.cpp
- Added shadow bias code to ShadowsRes. Solves an issue that caused [shadow acne](https://digitalrune.github.io/DigitalRune-Documentation/html/3f4d959e-9c98-4a97-8d85-7a73c26145d7.htm) to appear for resolutions greater than 4096.
- Added ImproveShadowLOD feature. Restores missing shadows details and improves their quality. Disabled by default for performance reasons. [Video Demonstration](https://www.youtube.com/watch?v=ILb1-zcFUOU)
- Replaced old SkipIntro code with new code. Fixed a bug that prevented the start menu video from playing.
- Disabled SkipIntro by default.
- Added second mode to FramerateFluctuationFix. (1 = 60 FPS | 2 = 30 FPS).
- Enabled FramerateFluctuationFix by default.
> [NFSMW] [NFSPS] [SH3] updates, bug fixes, shadow improvements

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
- data/SilentHill3.WidescreenFix/scripts/SilentHill3.WidescreenFix.ini
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
- source/NFSUnderground.WidescreenFix/dllmain.cpp
- source/NFSUnderground2.WidescreenFix/dllmain.cpp
- source/SilentHill3.WidescreenFix/dllmain.cpp
- Added code to enable HD_GROUP texture on start screen.
- Added code to change start screen text for ImproveGamepadSupport.
- Added option for BrakeLightFix.
- Added code to change start screen text for ImproveGamepadSupport.
- Renamed HudWidescreenMode to HUDWidescreenMode.
- Added code to change start screen text for ImproveGamepadSupport.
- Added DisableMotionBlur. This was added so people wouldn't need to modify their registry.
- Renamed HudWidescreenMode to HUDWidescreenMode.
- Added code to change start screen text for ImproveGamepadSupport.
- Added code for front-end gamepad actions that were either unused or not assigned correctly.
- Restored LB/RB (L1/R1) front-end functionality.
- Replaced "P" key emulation with new remapping code. _Note: old code has been commented, not …
> [NFS] [SH3] More features and bug fixes

- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- readme.md
- source/NFSUnderground.WidescreenFix/dllmain.cpp
This is a fix for a bug in the original game code, not a problem with WidescreenFix, but as explained in #862, this seems like a good place to include it.
When motion blur or light trails are turned on, the background of magazine covers are black.
[Example with Light Trails disabled](https://i.imgur.com/oILt4B9.png)
[Example with Light Trails enabled](https://i.imgur.com/miSF6Sf.png)
Let me know if you think the patch is too big for the project to take it.
Closes #862.
**TLDR** rendering surface on which background was drawn is cleared during the render of the car.
The rendering of the screen is divided in three steps:
1. 2D Background Renderer. Seems to be used only to render the background of magazine covers.
2. 3D Scene Renderer. Used to render everything that is 3D.
3. 2D Foreground …
> [NFSU] Black Magazine Cover Fix

- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- source/NFSProStreet.GenericFix/dllmain.cpp
- source/NFSUndercover.GenericFix/dllmain.cpp
Based on issue https://github.com/ThirteenAG/WidescreenFixesPack/issues/877#
This is an important bug fix, as the current releases don't work correctly for any aspect ratio other than 16:9.
[NFSUC]
- Fixed critical aspect ratio bug
- Added Scaling = 1 for proportionally correct image
- Removed HUDWidescreenMode and automated the code based on aspect ratio
[NFSPS]
- Fixed critical aspect ratio bug
- Added Scaling = 2 for proportionally correct image
> [NFSUC][NFSPS] aspect ratio bug fix, additional scaling options

- source/SilentHill2.WidescreenFix/dllmain.cpp
I have updated Silent Hill 2 Enhanced Edition to be able to change screen resolutions from inside the game.  As such I needed the ability to run this code more than once since I need to run it each time the resolution changes.
Running either `MakeInline()` or `hook::pattern()` more than once would crash the game.  So, this update basically makes it so that the `MakeInline()` is only run on the first call to `Init()`.  It also makes it so that the `hook::pattern()` call is static so that it only runs once and stores the results.
I made these changes everywhere except in the `if (bFullscreenImages && bFix2D)` section because we are not using this section in the Silent Hill 2 Enhanced Edition.
> [SH2] Update to allow `Init()` to be run mulitple times

- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
- source/NFSUnderground2.WidescreenFix/dllmain.cpp
Brief:
There's game crashes on multicores CPUs - reading 0xAAAAAAAA pointer, the only function that sets this value is MemoryPool::AllocateMemory and it is have mutex lock, may be problem is in bWareMalloc which is modifing MemoryPool without mutex lock, idk, this crashes happens so randomly so I can't test it.
The common fix is setting single core affinity on WHOLE process, which is causing performance issue: my 2.5 GHz Kaby Lake can't event provide 60 FPS. Is Kaby Lake weaker than Pentium 4? No, this is due to Nvidia drivers for Pascal.
Current NFSU2 WSFix version is also setting single core affinity on whole process.
In this pull request, only threads that are created directly by the game gets single core affinity, which is completly solving both game crashes and performance issues. …
> [NFSU2] Performance improvement

- source/SplinterCellChaosTheory.WidescreenFix/dllmain.cpp
https://github.com/ThirteenAG/WidescreenFixesPack/issues/979
Fix other misaligned texts for italian version of the game.
> SCCT: Fix other misaligned texts for italian ver

- source/SplinterCellChaosTheory.WidescreenFix/dllmain.cpp
Fixed another misaligned text in the last level for the Italian version of the game:
> SCCT: Fix another misaligned text for italian ver

- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- source/NFSUndercover.GenericFix/dllmain.cpp
This will increase/restore the visible scenery on the screen, as well as reduce culling while going around.
This does NOT fix flickering scenery (in shadows/envmap/main view). That is caused by some other bug in the game.
Examples:
Before:
After:
> [NFSUC] implement scenery improvements

- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- readme.md
- source/NFSUnderground.WidescreenFix/dllmain.cpp
This implements the same FPS limiter adjusters from Underground 2 to Underground.
The only difference is that the game either renders or reports the framerate at 2x the amount, but internally it's running at half rate.
This can be proven by playing around with the debug camera - if it goes over 99FPS, you can't turn over 180 degrees.
(I'm still testing this, I might add one more thing. races seem to end quicker than expected)
> [NFSU] implement FPS limit adjustments

- source/NFSUnderground.WidescreenFix/dllmain.cpp
To avoid possible crashes and hangs with high FPS limits, the FrameSeconds var needed to be limited to max 120. Game doesn't like it for whatever reason, so I'll leave it be.
> [NFSU] framelimit bugfix

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- readme.md
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSUnderground.WidescreenFix/dllmain.cpp
(also fixed the default inireader value for NFSU FPS limit)
- sim can now run at any framerate
- motion blur can now be explicitly disabled (meaning: without affecting other effects such as screen flashes or light trails)
> [NFSC] FPS limit adjuster & proper motion blur disabler

- source/NFSCarbon.WidescreenFix/dllmain.cpp
A bug fix for non-responsive world map cursor by scaling the float constants it uses by the frametime (used 1/60 as the default frametime for scaling)
> [NFSC] fix worldmap cursor update constants

- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- readme.md
- source/NFSProStreet.GenericFix/dllmain.cpp
Same as others, you can adjust frametime of the Sim and the renderer.
Also included is a workaround for the boost grip gain - this value needs to scale with the framerate/frametime, otherwise the grip addition becomes too big and therefore the drag staging (burnout) becomes way too easy to do and you gain max grip super fast.
Probably the proper way to fix this would be to make these values dynamically change with the frametime currently on the screen.
Yes, this is technically a _gameplay_ modification included in here, but it's for the sake of fixing it caused by high FPS.
> [NFSPS] implement frametime/framerate adjusters

- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
Bugfix for MW and Carbon - 1/60 value was shared for other things in the game, not just frametime, so this makes it apply only to the timestep values and nothing else.
This fixes the wrong time text in Challenge Series menus.
> [NFSMW/C] avoid other time scalars

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
Added extra clarification to ini
0 isn't disabled limiter, but is disabling the patches
Limiter itself can be "disabled" but probably in a very specific way (sim engine still needs to tick).
> [NFS] clarify disabled state for FPSLimit

- source/NFSProStreet.GenericFix/dllmain.cpp
- source/NFSUnderground.WidescreenFix/dllmain.cpp
Also a fix for Pro Street to actually dereference the grip boost values it modifies instead of directly setting them
> [NFSU] fix sticky steering for high FPS usage

- source/NFSUnderground2.WidescreenFix/dllmain.cpp
Forgot to dereference the value for the smokeable frametime, it was causing crashes
> [NFSU2] bugfix for the smokeable frametime deref

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- includes/stdafx.h
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
- source/NFSUndercover.GenericFix/dllmain.cpp
- source/NFSUnderground.WidescreenFix/dllmain.cpp
- source/NFSUnderground2.WidescreenFix/dllmain.cpp
- Created `WindowedModeWrapper` namespace to consolidate the windowed mode hooks into a single place - this is not only usable in NFS, but in various other games (see my [UbiTMNTHax](https://github.com/xan1242/UbiTMNTHax) - I used this exact code)
- Reimplemented all NFS games to use the WindowedModeWrapper instead - now the windows are created properly without any fuss
- NFS Undercover - broke up the scenery LOD hacks and set the defaults for them to be DISABLED - this is unfortunately buggy because of the model limitation the game imposes. The hacks unto themselves work, they increase visible scenery, but the renderer culls them away.
> Various improvements and fixes

- source/Psychonauts.WidescreenFix/dllmain.cpp
Black Velvetopia features its own unique strike flash effect not covered by the existing fix.
This PR updates the patch to account for the variant.
Before:
After:
Technically, this does stretch the texture, but it appears so briefly and is so jarring without this adjustment that I believe it's fine here.
> Psychonauts: Fix strike flash in Black Velvetopia

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
- source/NFSUndercover.GenericFix/dllmain.cpp
- source/NFSUnderground.WidescreenFix/dllmain.cpp
- source/NFSUnderground2.WidescreenFix/dllmain.cpp
- Hack is stable enough to become the default
- Fixes issues with too fast cameras, slow challenge series intros, too fast animated textures, etc.
> [NFS] update FPSLimit default to autodetect refresh rate

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
- source/NFSUndercover.GenericFix/dllmain.cpp
Better description of what FPSLimit actually did in MW and above.
It didn't limit FPS of the game, but the Sim engine. The renderer is independent of this rate.
Higher this rate, more responsive and faster everything is in the gameplay.
A good thing to do would be to probably find a way to unlock this rate to run as fast as possible.
> [NFSMW+] Rename FPSLimit to SimRate

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
- source/NFSUndercover.GenericFix/dllmain.cpp
Further testing shows that it wasn't necessary.
When you match FPS for both the game loop and the Sim engine, everything runs fine.
For example - you target 400FPS, the game renders at about 400FPS, the Sim (the actual car simulation) runs fine at 400Hz and the game runs at mostly full speed (depending on the renderer)
If you target 75FPS and the game renders at 75FPS, but you set the Sim to run at 1000Hz, then issues start to arise. The rest of the game is too slow to catch up with the actual gameplay (cameras not reacting to car movements fast enough).
If you target 1000FPS, but the game renders at 75FPS, then it's going to run super slow.
The console versions target 30FPS but has the gameplay loop at 60FPS (because of NTSC refresh rate). Some things run slightly slower (FE animations), …
> [NFSMW+] disable SimRate limiter

- source/NFSCarbon.WidescreenFix/dllmain.cpp
This scales the constants from their original values instead of re-defining them.
> [NFSC] read world map scalars before setting

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSUnderground2.WidescreenFix/dllmain.cpp
This will scale the length of the NOS trails with the desired framerate defined with SimRate to make it behave like the stock game.
Everything should be described in the ini entries. The trail becomes longer with the difference between SimRate and render FPS. For this reason, the console entries have longer trail distances.
The longer the trail distance is, less aligned it is with the car and more it clips through, hence why I added the option FixNOSTrailPosition.
This potentially could be fixed with some math in CarRenderInfo_RenderFlaresOnCar_Hook, but I'm honestly too stupid to figure that one out.
One thing I have to note - the hook in 0x00745038 is extremely clean. So clean, in fact, that it doesn't affect game code whatsoever. For some reason there is just one instruction below the …
> [NFS] nos trail length fix + adjuster

- includes/stdafx.cpp
I'm not sure if there was a reason for these formulas to be written the way they were (like accuracy or weird edge cases or something), but if there were none, this should look a bit cleaner and use a bit fewer math function calls.
> Do less math in common FOV calculations

- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
- Runtime checks were causing crashing in Debug build configurations
- LazyHook in ProStreet was causing issues with settings file loading on slower machines, disabling it fixes it. Vitality works without it now.
> [NFSPS/C] disable runtime checks & remove LazyHook

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
- includes/stdafx.h
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
- source/NFSUndercover.GenericFix/dllmain.cpp
- source/NFSUnderground.WidescreenFix/dllmain.cpp
- source/NFSUnderground2.WidescreenFix/dllmain.cpp
Added new modes: `(1 = Borderless scaled | 2 = Borderless stretch | 3 = Borderless no scale | 4 = Border | 5 = Border with resizing)`
This is not backwards compatible, so users should recheck their configs.
1 allows for supersampling, so feel free to go above the native resolution in supported games.
> add more windowed modes

- source/NFSProStreet.GenericFix/dllmain.cpp
The game has a memory leak or something of the sort causing it to crash after a very long play session.
The crashes always happen after race is finished and the post race screen is exited, which indicates that there might be something going on with it when it creates the screen.
Berkay and I suspect that it might have something to do with the leaderboards, shadows, stats, or something similar of the sorts, since this apparently does NOT happen in v1.0, only in v1.1 (regardless of Battery or Vitality NoCD).
Currently, this version of the fix skips UploadShadowStateManager from being created at all, which could fix the crashes in theory. It needs testing to be 100% sure if it works.
> [NFSPS] rewrite postracefix & potential fix for crashes after 4+ hours

- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- source/NFSProStreet.GenericFix/dllmain.cpp
- Added a fix for a memory leak while car damage is enabled (explanation below)
- Fixed patterns to support the demo versions (which are also DRM free!)
- Added an (attempted) PunkBuster disabler
- Added SkipFEBootflow option (mainly for the demo builds but also works in final)
OK so, the memory leak fix is a pretty big one.
Simply put - someone at Black Box forgot to free the memory pools for car damage (and their vertex buffers, DamagePool and DamageVBPool respectively) during runtime. This causes a memory leak which usually results in a crash after about 4 hours of playback.
(The time until crash varied on your free memory + free memory in the game's address space, which is 32 bits, non large address aware by default)
The fix consists of telling the game to release the two memory pools …
> [NFSPS] big update

- source/NFSProStreet.GenericFix/dllmain.cpp
Fixed an issue with the depth buffer not scaling correctly for widescreen aspect ratios. This error effected the in-game motion blur and specific ReShade effects that relied on the depth buffer.
> [NFSPS] Fixed aspect ratio bug

- data/SonicHeroes.WidescreenFix/scripts/SonicHeroes.WidescreenFix.ini
- source/SonicHeroes.WidescreenFix/dllmain.cpp
This is a reimplementation of the frame sync / FPS limiter function in the game.
It isn't a perfect 16.67ms for some odd reason, but it's way smoother than whatever the game ships with.
I've also included a disabler for it, so you can limit the FPS via your GPU's control panel instead for a perfect 16.67ms limit.
I'll probably iterate on this to try to make the game actually run at higher than 60FPS later, but for now this will do.
> [Sonic Heroes] implement better FPS limiter

- source/SonicHeroes.WidescreenFix/dllmain.cpp
Sorry for many pull requests lol
I've just noticed that the new frame syncing causes FMV playback to stutter. This will simply use the old sync function during FMV playback.
> [Sonic Heroes] fix movie stuttering

- data/SonicHeroes.WidescreenFix/scripts/SonicHeroes.WidescreenFix.ini
- source/SonicHeroes.WidescreenFix/dllmain.cpp
Implemented this into code: https://github.com/ThirteenAG/d3d8-wrapper/pull/5
I've set Sleep-Yield as default for now. If things go haywire, return defaults to Thread-Lock instead.
I see no measurable inaccuracy between the two. Sleep-Yield is less resource intensive, so it's wiser to use that IMO.
> [Sonic Heroes] implement FPS limiter from d3d8-wrapper

- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- source/NFSProStreet.GenericFix/dllmain.cpp
Fixes LAN mode for Windows 11 users by forcing the address family to AF_INET (IPv4) (or AF_INET6 (IPv6)).
Microsoft broke AF_UNSPEC (unspecified) for whatever reason in Win11.
Note that this is a client only fix. The server itself (specifically Rebroadcaster) also needs the exact same fix.
As hooking Winsock2 is blocked by the OS, there is no choice but to patch the executable directly (or hook the C runtime). I've attached the necessary file in here as well. It needs to be placed in the ONLINE folder of the game.
[rebroadcasterlan.zip](https://github.com/ThirteenAG/WidescreenFixesPack/files/11668450/rebroadcasterlan.zip)
Furthermore - the exe was patched to re-enable console logging, so you can see what is going on exactly.
To launch a server through the console, you must first launch …
> [NFSPS] implement LAN fix for win11

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
[NFS]
- Improved the INI file readability for all of the new features that were added.
[NFSPS]
- Changed the default registry brightness value from 68 to 50. This was causing the game to appear washed out when `WriteSettingsToFile` was used.
[NFSMW]
- Removed `ForceEnableMirror` since this feature is now redundant with existence of the HD Reflections mod.
> [NFS] Improved INI file readability

- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- ShadowRatio will only scale up to 16:9 so shadows remain visible for ultra wide aspect ratios. This is a temporary workaround until a proper solution is implemented.
- ShadowBias has been made less aggressive so less detail is lost at higher shadow resolutions.
> [NFSMW] Updated ShadowRatio & ShadowBias

- source/NFSMostWanted.WidescreenFix/dllmain.cpp
ShadowRatio values will be updated when the window is resized. Forgot to add this to my previous commit.
> [NFSMW] ShadowRatio - Resizable Window

- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
Shadow code has now been reworked with the same logic behind the regular FOV fix.
This fixes issues with shadows disappearing for ultrawide users, for example. (check https://github.com/ThirteenAG/WidescreenFixesPack/issues/1085 )
In addition to that, the following was done:
- Shadow resolution stuff has been moved into its own namespace `ShadowRes`
- Added an option to optionally disable bilinear filtering of textures on Radeon cards (instead of it being forced on)
- AutoScaleShadowsRes and ImproveShadowLOD are now on by default -- this is done because majority of users turn this on anyway
- Window resizing also updates the shadow resolution and related things
- Ini formatting has been updated with semicolon inline comments instead of double-slash (which was incorrect) -- this will be …
> [NFSMW] rework shadow code

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini
- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
Replaces all double-slashes with semicolons, which is the correct way to comment in the .ini format!
> [NFS] update ini comment markers

- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- Added a GRAPHICS section to the .ini to de-clutter the MISC section - THIS WILL BREAK BACKWARDS COMPATIBILITY WITH THE OLD INIs, users must update .ini in the next version
- Added option to control g_LightStreaksEnable
- Added option to control g_BleachByPassEnable
> [NFSMW] implement unused graphics settings + ini reformat

- data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini
- source/NFSCarbon.WidescreenFix/dllmain.cpp
I've decided to give NFSC the same treatment as MW in this regard.
- ini now has a GRAPHICS section to reduce clutter - THIS WILL BREAK COMPATIBILITY WITH OLD INIS - users have to update
- ported over rate limiters from NFSMW_XenonEffects
There is still a slight TODO with this - the rate limiters need proper frametime measurement to work properly. Currently it's using frame counting which is very inaccurate. It's _fine_ for now though. It reduces the absolute milkfest coming out of the car at high FPS.
> [NFSC] INI reformat + XenonEffect limiters

- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
I think it's about time this was fixed.
I'll consider making it functional later.
Oh and it works in resizable windows too, so when you resize the window and re-enter the menu it actually shows the current window size.
> [NFSMW] add resolution text fix for the VO menu

- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
RainDropletsScale was missing in MW and UG2.
NoOpticalDriveFix was missing in UG2.
> [NFSU2] [NFSMW] re-add some ini options

- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSUnderground.WidescreenFix/dllmain.cpp
- source/NFSUnderground2.WidescreenFix/dllmain.cpp
Here's the last one for today I hope - minimum resolution clamp for NFS games that have assignable resolutions.
This is to prevent any crashes from happening because you can't run the games in an extremely low res.
> [NFSC and older] clamp min res to 32x32

- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- source/NFSProStreet.GenericFix/dllmain.cpp
With the release of NFS_XtendedInput v1.18 I feel comfortable removing `ImproveGamepadSupport` for Pro Street.
I've ironed out most of the major bugs surrounding the configuration menu and restructured how the mappings work. Now, the controls are saved per user profile.
Link to the current version at the time of writing:
https://github.com/xan1242/NFS-XtendedInput/releases/tag/1.18
Please note that users will have to set up XInput to properly control the game. So if they have a non-XInput compliant controller, they will have to work around it (DS4Windows, Steam Input, X360CE, ScpServer, Steam Controller with Gyro, all of these were tested and working).
There are Win7 builds available. Everyone using WS/Generic Fix should avoid these unless they know what they're doing.
In case users have …
> [NFSPS] remove ImproveGamepadSupport

- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
Remember how @AeroWidescreen made all the shadows sharp by default?
This makes it optional and available for all GPUs that support INTZ texture format.
I've also separated the VendorID forcing into its own thing, which will affect the render path + capabilities exposed in the Video Options menu. It's set to NVIDIA as it was before.
That being said - there is one peculiar thing happening with the soft shadows. Depending on the camera angle, the soft shadows can either completely break (they become sharp again) or change their edges a bit.
This leads me to believe that the feature is actually broken from day one and the shadows were meant to become sharper as the objects are closer to ground. Either that, or it's very low res/sample rate.
Either way, it's good to have it as an option for …
> [NFSMW] add shadow + other render options

- data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
A small hack to optionally disable the blurring effect on the depth buffer stencil. This will result in stencil shadows (think of GTA San Andreas shadows).
This slightly breaks the shader so the fade-in effect is broken on it (the far shadows pop in into view).
> [NFSMW] add sharp shadow option for stencil types

- data/SonicHeroes.WidescreenFix/scripts/SonicHeroes.WidescreenFix.ini
- includes/stdafx.h
- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
- source/NFSUndercover.GenericFix/dllmain.cpp
- source/NFSUnderground.WidescreenFix/dllmain.cpp
- source/NFSUnderground2.WidescreenFix/dllmain.cpp
- source/SilentHill2.WidescreenFix/dllmain.cpp
- source/SonicHeroes.WidescreenFix/dllmain.cpp
- source/SplinterCellDoubleAgent.WidescreenFix/dllmain.cpp
The goal is to implement support for `std::filesystem::path` to support Unicode paths at the level of this plugin.
This does NOT patch the games themselves. The games will vary on how they behave when stored in Unicode paths. Sadly, NFS's file IO functions aren't capable of using Unicode paths and will need work.
What was changed:
- inireader was modified to read paths with the new method
- inireader was also modified with a new ini writer which replaces `WritePrivateProfileStringA` but otherwise functions exactly the same
- various functions in `stdafx.h` were modified to incorporate support for `std::filesystem::path`
- RegistryWrapper was modified to support `std::filesystem::path`
- reworked every NFS game and Sonic Heroes to support `std::filesystem::path` with custom user directory …
> Implement Unicode pathing support

- data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini
- source/NFSProStreet.GenericFix/dllmain.cpp
- Added an option for FE auto fitting for widescreen aspects below 16:9 but above 1.5555:1
- Added an option to force FE mode (widescreen and standard)
- Added an option to control FE scaling and removed ConsoleHUDSize (now just set 0.92 for same effect)
- Added extra patches to the existing widescreen checks in the game code
- FMVs now scale together with the FE scale to fix mismatched flashers and subtitlers
I'm planning to do this same deal for MW and Carbon.
> [NFSPS] FE & FMV scaling rework

- data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini
- data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini
- source/NFSUnderground.WidescreenFix/dllmain.cpp
- source/NFSUnderground2.WidescreenFix/dllmain.cpp
Same deal as MW and Carbon scalers pretty much.
I had to do some exotic workarounds due to my own stupidity (my Reshade fork hooks the same place in UG1).
HUD auto fitting isn't necessary as that's done automatically, therefore it's been disabled by default.
FMVs on the other hand benefit on 16:10 displays by having more height to display.
> [NFSU/U2] implement FE scaling

- source/NFSCarbon.WidescreenFix/dllmain.cpp
- source/NFSMostWanted.WidescreenFix/dllmain.cpp
- source/NFSProStreet.GenericFix/dllmain.cpp
As fixing the mouse is practically impossible without what XtendedInput does already, I've just decided to scale the window size from within XtendedInput to resolve this issue.
Done in coordination with this commit: https://github.com/xan1242/NFS-XtendedInput/commit/6567430e21db80cdac380a8b26bb8fe0a3cd981e
I'll also upload a new build of XtendedInput with these changes.
Underground & 2 will have to wait until I decide to update its XtendedInput.
> [NFSMW/C/PS] add FE scaling interop with XtendedInput

- source/NFSUnderground.WidescreenFix/dllmain.cpp
Added code that flips the if statement for if the best lap time should be displayed on the results screen or not.
This doesn't change behaviour for 16:9 displays, as the best lap hud element falls outside of the 16:9 aspect ratio range but on 21:9 displays an extra piece of text is visible.
> [NFSU] Remove Best Lap Time from Results Screen

- data/TonyHawksProSkater4.WidescreenFix/Game/scripts/TonyHawksProSkater4.WidescreenFix.ini
- source/TonyHawksProSkater4.WidescreenFix/dllmain.cpp
Currently the field of view for the game seems fairly low at the default settings even when aspect corrected. This change allows for the user to change what the fov scaling is for the regular in game camera.
Example default settings:
Fov scale set to 1.4:
> THPS4: Fix for field of view not being aspect corrected

- data/SonicHeroes.WidescreenFix/scripts/SonicHeroes.WidescreenFix.ini
- source/SonicHeroes.WidescreenFix/dllmain.cpp
Added a detect for the demo version (which can be freely obtained from [Hidden Palace](https://hiddenpalace.org/Sonic_Heroes_(Nov_9,_2004_demo)))
It doesn't have the code for the demo mode and CD checks, so those are disabled for this build
> [Sonic Heroes] add demo/trial version detection

- source/CallOfCthulhu.WidescreenFix/dllmain.cpp
PROBLEM:
-Open Inventory Menu with [I]. 
Hover mouse over top-left icon (book) - instead the second icon (watch) will be selected.
-Click on Jack to view Heal Menu. 
Hover mouse over left-most square in grid - instead the second square will be selected.
-Watch the Heart Rate Monitor at top-right of the screen. 
Right-most Line Paper texture disappears leaving ink line over black screen.
SOLUTION:
-Added/Modified calculations for cursor boxes in inventory and heal menu.
-Found unused black square in inventory menu. Covered the right-most Line Paper with it. However, the ink line was being drawn at the top layer (on top of the black box). Adjusted the ink line to be between the black box and the inventory.
TESTING:
I've played up to Innsmouth with no issues. Only tested on 16:9 monitor as …
> [Call of Cthulhu] Fixed Inventory Menu Cursor Boxes and Heart Rate Monitor

- source/ResidentEvilRevelations2.FusionFix/dllmain.cpp
Add a fix for stretched FMVs for ReRev2.
Explanation:
FMV rendering uses a YUV decoding pixel shader with a crc of 0x9D190FC7 and a generic screenspace vertex shader with a crc of 0x1287841D. We hook D3DDevice9::DrawPrimitive, and if both of these shaders are active, we instead activate our own vertex shader (injected earlier) which resizes the verts according to 16:9 aspect.
> Fix stretched FMVs for Resident Evil Revelations 2.

- source/GTA3.WidescreenFix/dllmain.cpp
- scaling for 1st person sniper and rocketlauncher black borders;
- island loading screen text height and bottom screen offset
> more scaling patches
