ThirteenAG/WidescreenFixesPack

source/GTA3.WidescreenFix/dllmain.cpp
Otherwise the game keeps defaulting to Miles 2D
=> Fixes #296

source/HiddenandDangerous2.WidescreenFix/dllmain.cpp
Fixes black screen in  **Op. Challenger - Agent** cutscene
=> H&D2 black screen fix

data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini, data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini, data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini, data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini, data/SilentHill2.WidescreenFix/scripts/SilentHill2.WidescreenFix.ini, data/SilentHill3.WidescreenFix/scripts/SilentHill3.WidescreenFix.ini, data/SilentHill4.WidescreenFix/scripts/SilentHill4.WidescreenFix.ini
Someone made a good [suggestion](https://github.com/ThirteenAG/WidescreenFixesPack/issues/417#issuecomment-366474967), so I decided to make some changes to all (SH / NFS) ini files while I was at it.
**SH2**
- Added descriptions to a lot more features.
- Changed IncreaseNoiseEffectRes to 0 since it's a very subjective setting.
- Made a few grammar and punctuation changes.
**SH3** 
- Added descriptions to a lot more features. 
- Changed ReduceCutsceneFOV to 0 since it should have been at 0 to begin with. 
- Changed FrameRateFluctuationFix to 0  because of the issues it causes people with weaker hardware. 
- Made a few grammar and punctuation changes.
**SH4** 
- Added descriptions to a lot more features.
- Mentioned the drawback of Fix2D.
**NFSU**  
- Changed "Use with HudFix" to "Use with …
=> Ini changes

source/GTA3.WidescreenFix/dllmain.cpp
Fixes player model view in a skin selection menu.
=> GTA 3 Player Skin menu fix

source/GTA3.WidescreenFix/dllmain.cpp
Different hook pattern for Steam version compatibility.
=> GTA 3 Steam version fix

source/SonicHeroes.WidescreenFix/dllmain.cpp
Reverts ThirteenAG/WidescreenFixesPack#632
=> Revert "Heroes Vertical aspect direction + Zoom Scale"

data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini, source/NFSProStreet.GenericFix/dllmain.cpp
I don't really know what I'm doing here, so apologies if I got any of the code wrong. I did test it to confirm that it's working.
=> [NFSPS] Added FixHUD Option

source/SplinterCellChaosTheory.WidescreenFix/dllmain.cpp
=> SCCT: Fix for polish ver. of game

source/SplinterCellChaosTheory.WidescreenFix/dllmain.cpp
=> SCCT: Fix for italian ver. of game

source/SilentHill2.WidescreenFix/dllmain.cpp
This fixes issue with James disappearing.  See: [elishacloud/Silent-Hill-2-Enhancements@#455](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/455)
=> Fixes issue with when running code multiple times

data/GTA2.WidescreenFix/scripts/GTA2.WidescreenFix.ini, source/GTA2.WidescreenFix/dllmain.cpp
- camera height adjustment keys in INI
- camera min & max limits in INI
=> various fixes

source/NFSProStreet.GenericFix/dllmain.cpp
Because the ViTALITY exe is protected and dumps its contents to memory during launch, all syscalls default to NULL. With a simple lazy hook, `WriteSettingsToFile` is now compatible
=> [ProStreet] Make `WriteSettingsToFile` compatible with a lazy hook

data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini, source/NFSMostWanted.WidescreenFix/dllmain.cpp
I'm not sure how much you like function hooks but here you go. If you like this, I can backport it to other games too.
=> [NFSMW] implement windowed mode

data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini, data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini, source/NFSUnderground.WidescreenFix/dllmain.cpp, source/NFSUnderground2.WidescreenFix/dllmain.cpp
Basic windowed mode implementation. Currently does NOT support dynamic resolution resizing.
(Doing a PR and not pushing, testing things out... Will merge as soon as appveyor completes the build)
=> [UG1 | UG2] implement windowed mode

readme.md
With all the new features added, the README was left neglected, so I added the points for windowed mode and Undercover shadow/scenery patches.
=> Update README, new features

data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini, readme.md, source/NFSMostWanted.WidescreenFix/dllmain.cpp
Implement the same thing from the previous PR for Carbon frametime (even uses same pattern for timestep detection)
=> [NFSMW] frametime/frame limiter adjustment

data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini, readme.md, source/NFSUndercover.GenericFix/dllmain.cpp
Like others, implemented total frametime adjuster and added a proper motion blur disabler.
Also fixed a minor bug with pattern detector I used previously during shadow fixing wrongly...
=> [NFSUC] implement framerate/frametime adjusters and motion blur disabler

data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini, data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini, data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini, data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini, data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini, data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini, includes/stdafx.cpp, includes/stdafx.h, source/NFSCarbon.WidescreenFix/dllmain.cpp, source/NFSMostWanted.WidescreenFix/dllmain.cpp, source/NFSProStreet.GenericFix/dllmain.cpp, source/NFSUndercover.GenericFix/dllmain.cpp, source/NFSUnderground.WidescreenFix/dllmain.cpp, source/NFSUnderground2.WidescreenFix/dllmain.cpp
- Added desktop / primary monitor refresh rate read function to stdafx.cpp
- Implemented functionality to all NFS games (set -1 in FPSLimit to use)
=> [NFS] implement refresh rate autodetection

data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini, data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini, data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini, source/NFSUnderground2.WidescreenFix/dllmain.cpp
Also polished up some ini descriptions.
=> [NFSU2] improve frametime adjusters and stuff related to it

source/NFSUnderground2.WidescreenFix/dllmain.cpp
After further testing, even 120 is buggy even at higher actual framerates...
=> [NFSU2] revert AnimScene framerate to 60

data/GTA2.WidescreenFix/ddraw.ual, data/GTA2.WidescreenFix/scripts/GTA2.WidescreenFix.ini, data/GTA2.WidescreenFix/wndmode.ini, source/GTA2.WidescreenFix/dllmain.cpp
- HOR+ support.
- Fix menu and player arrow misalignment.
- Use original window width and height variables.
=> GTA2 update

data/GTA2.WidescreenFix/ddraw.ual, data/GTA2.WidescreenFix/dinput.ual, data/GTA2.WidescreenFix/scripts/GTA2.WidescreenFix.ini, data/GTA2.WidescreenFix/wndmode.ini, source/GTA2.WidescreenFix/dllmain.cpp
=> GTA2 add dinput.ual

data/GTA2.WidescreenFix/scripts/GTA2.WidescreenFix.ini, source/GTA2.WidescreenFix/dllmain.cpp
- Extends hud to screen corners.
- Fix frontend.
- Fix intro crash in windowed mode.
- Skip credits.
- Skip sampman delay.
- Code cleanup
=> GTA2 improvements

data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini, source/NFSCarbon.WidescreenFix/dllmain.cpp
implements the fix for issue https://github.com/ThirteenAG/WidescreenFixesPack/issues/1261
=> [NFSC] implement XenonEffect fix

source/NFSCarbon.WidescreenFix/dllmain.cpp
per @AeroWidescreen's request; https://github.com/ThirteenAG/WidescreenFixesPack/issues/1232
=> [NFSC] lighting fix update (mirror) redux

data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini, source/NFSProStreet.GenericFix/dllmain.cpp
fix for issue https://github.com/ThirteenAG/WidescreenFixesPack/issues/1265
=> [NFSPS] implement xenon effect fix

data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini, source/NFSProStreet.GenericFix/dllmain.cpp
- Updated ini with better descriptions
- Added XtendedInput detection
- Added achievements disabler to improve stability
- Added "Booster pack" FNG disabler
- Added version detection for the MultiFix portion to avoid unnecessary patching
=> [NFSPS] add achievement disablers and various improvements

data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini, data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini, data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini, data/NFSUndercover.GenericFix/scripts/NFSUndercover.GenericFix.ini, data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini, data/NFSUnderground2.WidescreenFix/scripts/NFSUnderground2.WidescreenFix.ini, source/NFSProStreet.GenericFix/dllmain.cpp
Fixed random crashing caused by the previous commit and updated the INI descriptions for the `Scaling` option.
=> [NFSPS] Fixed Crash

source/SonicHeroes.WidescreenFix/dllmain.cpp
Even more improved frame sync. Now fully stable and locked at 16.67ms (60FPS) (loading stutter notwithstanding).
Now using only QueryPerformanceCounter and not relying on chrono or other Win32 shenanigans.
=> [Sonic Heroes] even better sync

source/NFSProStreet.GenericFix/dllmain.cpp
- Disabled game freezing on focus loss during online/LAN play to avoid disconnects
- Added a custom input disabler for this situation as well
=> [NFSPS] implement online window focus checks

source/NFSProStreet.GenericFix/dllmain.cpp
I forgot to add the pattern for this address
=> [NFSPS] add pattern for OnlineActiveGameManager

source/NFSMostWanted.WidescreenFix/dllmain.cpp
Reverts ThirteenAG/WidescreenFixesPack#1352
I'm currently working on fixing shadows which will conflict with this PR. This will have to be redone later.
=> Revert "[NFSMW] ShadowRatio - Resizable Window"

source/NFSMostWanted.WidescreenFix/dllmain.cpp
=> [NFSMW] remove shadow ratio var

source/NFSProStreet.GenericFix/dllmain.cpp
- Removed regex checks for IPv6 because the IP address input box is only 15 chars wide
- Removed unused PostRace code from the old MultiFix which has been replaced with the new one
- Also tried implementing the PR https://github.com/ThirteenAG/WidescreenFixesPack/pull/1362 but ultimately gave up due to broken code in the PR itself
=> [NFSPS] code cleanup

data/NFSProStreet.GenericFix/scripts/NFSProStreet.GenericFix.ini, source/NFSProStreet.GenericFix/dllmain.cpp
- finally managed to separate FMV FE scaling from everything else - now movies will have proper flashers and subtitlers separate from the rest of FE scaling
- added an option to control FMV scaling
- added an option to auto fit FMVs on other aspect ratios
I don't have an efficient way to spam FMVs to the game for testing, but so far so good.
=> [NFSPS] reworked FE scaling v2

data/NFSCarbon.WidescreenFix/scripts/NFSCarbon.WidescreenFix.ini, data/NFSMostWanted.WidescreenFix/scripts/NFSMostWanted.WidescreenFix.ini, source/NFSCarbon.WidescreenFix/dllmain.cpp, source/NFSMostWanted.WidescreenFix/dllmain.cpp
- Implemented same FE scaling settings as in Pro Street
- cleaned up some old stupid code
Underground & 2 are left on the TODO list since they're slightly different...
@AeroWidescreen this should supersede your HUD resizers
=> [NFSMW/C] implement FE scalers + cleanup

source/NFSMostWanted.WidescreenFix/dllmain.cpp
Added a wildcard to a byte pattern used for `LightStreaksEnable` and `BleachByPassEnable`. This was causing the game to crash at launch when using the Xbox 360 shader mod.
=> [NFSMW] Updated Byte Pattern 

includes/psp/inireader.h, makefile.lua, premake5.lua, source/GTACTW.PPSSPP.FusionMod/makefile, source/GTALCS.PPSSPP.ImVehLM/makefile, source/GTALCS.PPSSPP.Project2DFX/makefile, source/GTALCS.PPSSPP.WidescreenFix/makefile, source/GTAVCS.PPSSPP.ImVehLM/makefile, source/GTAVCS.PPSSPP.Project2DFX/makefile, source/GTAVCS.PPSSPP.WidescreenFix/makefile, source/MidnightClubLARemix.PPSSPP.FusionMod/makefile, source/PPSSPP.XboxRainDroplets/makefile, source/SplinterCellEssentials.PPSSPP.FusionMod/makefile, source/TheWarriors.PPSSPP.FusionMod/makefile
=> update PS2 and PSP buildscripts

data/NFSUnderground.WidescreenFix/scripts/NFSUnderground.WidescreenFix.ini, source/NFSUnderground.WidescreenFix/dllmain.cpp
I'm not familiar with the utilities, and unable to check whether it compiles at all (don't have MSVC installed, and cross-compiling seems to be not supported?), so pardon if there are any problems. Also not sure about the style. Please test and comment, will do necessary changes.
=> [NFSU] Add audio sampling rate fix

.github/docs/re1.md, data/ResidentEvil.FusionFix/scripts/ResidentEvil.FusionFix.ini, source/ResidentEvil.FusionFix/dllmain.cpp
There was something missing in this slow-paced game with fixed camera angles... More frames!
Tested on the Steam version.
I didn't test it a lot.
I played at 144 FPS until the "Jill Sandwitch" part, so I don't know if something might be broken later in the game.
=> re1: Unlock FPS with "Variable" framerate

source/GTA3.WidescreenFix/dllmain.cpp
Wsfix was missing patches for scaling vertical resolutions of CHud and CRadar elements from `FixHUD()`, but not `ApplyIniOptions()` fsr. This led to e.g. sniper scope and radar sprites being incorrectly stretched by PS2's Y res of 448.0f instead of 480.0f!
=> missing fixes for GTA3 vertical scaling
